import { ThemeProvider } from "@/components/providers/ThemeProvider";
import type { Metadata } from "next";
import { open_sans } from "@/lib/fonts";
import "./globals.css";

export const metadata: Metadata = {
    title: "Eklavya",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={open_sans.className}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="light"
                    enableSystem
                    storageKey="theme"
                >
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
}
