import { ThemeProvider } from "@/components/providers/ThemeProvider";
import type { Metadata } from "next";
import { open_sans } from "@/lib/fonts";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import AuthProvider from "@/components/providers/auth-provider";
import ModalProvider from "@/components/providers/modal-provider";
import QueryProvider from "@/components/providers/react-query-provider";

export const metadata: Metadata = {
    title: "Eklavaya",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={open_sans.className}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="light"
                    storageKey="theme"
                >
                    <AuthProvider>
                        <QueryProvider>
                            <>
                                {children}
                                <Toaster />
                                <ModalProvider />
                            </>
                        </QueryProvider>
                    </AuthProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
